name: key_generator_app
description: "تطبيق مولّد مفاتيح التفعيل المخصص لتطبيق مولد أوراق الإختبارات"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # مكتبة التشفير لتوليد المفاتيح بنفس خوارزمية SHA-256
  crypto: ^3.0.3

  # مكتبة دعم الخدمات والنظام للتعامل مع الحافظة (Copy/Paste)
  flutter_services:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # دعم الخطوط العربية
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
