name: generator_app
description: "تطبيق مولّد مفاتيح التفعيل المخصص لتطبيق طالوت الهاشمي للاتصالات المحلية"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # مكتبة التشفير لتوليد المفاتيح بنفس خوارزمية SHA-256
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
